name: "Build Nuitka Wheel"
description: "Handles building manylinux compatible wheels for Nuitka."

inputs:
  tag:
    description: Python tag to use.
    required: true
    default: "cp38-cp38"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.tag }}