name: "Build Nuitka Wheel"
description: "Handles building manylinux compatible wheels for Nuitka."

inputs:
  python-tag:
    description: Python tag to use.
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.python-tag }}